### ISSUE TITLE
USCIS Processing times

### ISSUE THREAD

**Issue by arielsvn** [arielsvn/arielsvn.github.io#3]
Given the processing times for the different cases of USCIS, can I estimate the likelihood that a case will be processed in a given time??

I'll calculate what's the chance of USCIS taking 12 months to process a permanent residency application, and create an application that does the same for all cases in each office.

The app will have three main pages:

- Landing page, with general information and links to each one of the cases

- A page for each form type. 

- A page for each form type and a specific office.

### TODO
- [ ] Create script to query all USCIS endpoints and save the results as JSON
- [ ] Create Jekyll plugin to generate all pages from the downloaded data
- [ ] Convert USCIS data into the format required by Jekyll

**Comment by arielsvn** [comment]
Processing times for USCIS can be seen on https://egov.uscis.gov/processing-times/

There're two main URLs, https://egov.uscis.gov/processing-times/api/formoffices/I-485 returns the Service Centers associated with the FORM **I-485**

![image](https://user-images.githubusercontent.com/1882507/41134446-585cec56-6a9a-11e8-9d2a-b157267d214c.png)


And, https://egov.uscis.gov/processing-times/api/processingtime/I-485/SSC returns processing time information for FORM **I-485** and service center **SSC**

![image](https://user-images.githubusercontent.com/1882507/41134469-77135e50-6a9a-11e8-9615-c2688c09bb5a.png)

**Comment by arielsvn** [comment]
References:

- https://www.americanimmigrationcouncil.org/research/uscis-data-application-and-petition-processing-times

**Comment by arielsvn** [comment]
### Other ideas

It would be interesting to have a graph comparing the number of people that leave Cuba vs the number of applications for permanent residency received here. USCIS publishes [historical data](https://www.uscis.gov/tools/reports-studies/immigration-forms-data/data-set-all-uscis-application-and-petition-form-types) for all form types,  and I'm almost sure the data for Cuba  is also available

**Comment by arielsvn** [comment]
![image](https://user-images.githubusercontent.com/1882507/41210659-02652c8c-6d01-11e8-8097-6e6367283ddd.png)

**Comment by arielsvn** [comment]
Alternative font to proxima nova 
https://theultralinx.com/2013/04/free-alternative-font-gotham-proxima-nova/
